version: '3.8'
services:
  django:
    build:
      context: "WS"
      dockerfile: "Dockerfile"
    volumes:
      - ./WS:/django
    ports:
      - "8080:8080"
    command: python manage.py runserver 0.0.0.0:8080
    environment:
      - DJANGO_DB=sqlite3
